default:
  close:
    comment: ⚠️ This has been marked to be closed in $DELAY.
    delay: 604800000 # 7 days
labels:
  duplicate: close
  wontfix: close
  invalid: close
  "squash when passing": merge
  "rebase when passing": merge
  "merge when passing": merge
comments: []
commits:
  - action: label
    pattern: /merge when passing/i
    labels:
      - merge when passing
